CREATE FUNCTION ITN_NEPALI_FMT_DATE (IN datestring NVARCHAR(10))
Returns NPDT NVARCHAR(12)
LANGUAGE SQLSCRIPT
SQL SECURITY INVOKER
AS

BEGIN

NPDT :=
SUBSTRING(:datestring,0,4)
||'/'||SUBSTRING(:datestring,6,2)
||'/'||SUBSTRING(:datestring,9,2);

END;